### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/eclipse/sisu/equinox/embedder/internal/DefaultEquinoxEmbedder

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#79]
If I run tycho-snapshots I get the following error after the build **succeeds (!)**

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.580 s
[INFO] Finished at: 2021-04-20T06:54:28+02:00
[INFO] ------------------------------------------------------------------------
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/eclipse/sisu/equinox/embedder/internal/DefaultEquinoxEmbedder$2$1
	at org.eclipse.sisu.equinox.embedder.internal.DefaultEquinoxEmbedder$2.run(DefaultEquinoxEmbedder.java:207)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.eclipse.sisu.equinox.embedder.internal.DefaultEquinoxEmbedder$2$1
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 2 more

```

**Comment by sravanlakkimsetti** [comment]
We are getting the following errors while running surefire tests

!ENTRY org.eclipse.ecf.provider.filetransfer 4 0 2021-04-20 07:55:30.072
!MESSAGE org.eclipse.core.runtime.Status[plugin=org.eclipse.ecf.provider.filetransfer;code=4;message=Warning: Platform proxy API not available;severity2;exception=java.lang.NoClassDefFoundError: org/eclipse/core/net/proxy/IProxyService;children=[]]
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/core/net/proxy/IProxyService
	at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer.setupProxies(AbstractRetrieveFileTransfer.java:956)
	at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer.sendRetrieveRequest(AbstractRetrieveFileTransfer.java:886)
	at org.eclipse.ecf.provider.filetransfer.retrieve.MultiProtocolRetrieveAdapter.sendRetrieveRequest(MultiProtocolRetrieveAdapter.java:148)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.sendRetrieveRequest(FileReader.java:454)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.readInto(FileReader.java:384)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:107)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:166)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.handleRemoteIndexFile(AbstractRepositoryManager.java:730)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadIndexFile(AbstractRepositoryManager.java:724)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:666)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.getQueryableMetadata(P2TargetUtils.java:976)
	at org.eclipse.pde.internal.core.target.IUBundleContainer.getRootIUs(IUBundleContainer.java:766)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.getRootIUs(P2TargetUtils.java:1439)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.resolveWithPlanner(P2TargetUtils.java:1003)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.synchronize(P2TargetUtils.java:827)
	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:403)
	at org.eclipse.pde.api.tools.internal.ApiAnalysisApplication.setBaseline(ApiAnalysisApplication.java:247)
	at org.eclipse.pde.api.tools.internal.ApiAnalysisApplication.start(ApiAnalysisApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.equinox.internal.app.AnyThreadAppLauncher.run(AnyThreadAppLauncher.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.net.proxy.IProxyService cannot be found by org.eclipse.ecf.provider.filetransfer_3.2.601.v20201025-0700
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 23 more

This particular service is provided by https://download.eclipse.org/eclipse/updates/4.20-I-builds/I20210418-1800/plugins/org.eclipse.core.net.linux.x86_64_1.2.400.v20190924-1023.jar

There is a problem in resolving this.[Log](https://bugs.eclipse.org/bugs/attachment.cgi?id=286173)

**Comment by sewe** [comment]
FYI, I `git bisect`ed this (in the interval bac9ceaee9e945e8681abe7edc98309129cbe36e → 2d834d23cafebd247541d40367032e10e542d417) and came up with the following:

```
5feb9379522f3ab0f3cde5be88412cff8d085b2a is the first bad commit
commit 5feb9379522f3ab0f3cde5be88412cff8d085b2a
Author: Marc Miltenberger <Marc@Miltenberger.eu>
Date:   Mon Jun 19 20:45:29 2017 +0200

    Delete temporary directory after exit

:040000 040000 4170d3156140a44de07015a19a977c50bc0b6e02 1af9464f6a3a7bbf054b215c6997bde7877d0fb8 M	sisu-equinox
```

(Nb.: While the commit’s _Date_ is 2017, the change was really committed by Mickael Istria on 12 April 2021.)

**Comment by mickaelistria** [comment]
Those issues do not seem to be so related. @sravanlakkimsetti can you please open a different ticket?

**Comment by sravanlakkimsetti** [comment]
> Those issues do not seem to be so related. @sravanlakkimsetti can you please open a different ticket?

I believe both are same. If you see the [log](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Gerrit/4521/console) exact same error message is shown.
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/eclipse/sisu/equinox/embedder/internal/DefaultEquinoxEmbedder$2$1
	at org.eclipse.sisu.equinox.embedder.internal.DefaultEquinoxEmbedder$2.run(DefaultEquinoxEmbedder.java:207)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.eclipse.sisu.equinox.embedder.internal.DefaultEquinoxEmbedder$2$1
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 2 more

 I added contents from .log generated in that job.

**Comment by laeubi** [comment]
@sravanlakkimsetti as described above the error also occurs on **sucessfull (!)** builds the only issue seems that the stack is printed and the temp directory of course is not cleaned up.

**Comment by mickaelistria** [comment]
Thanks for the report, and @sewe for pointing to the right commit. Can you please create a commit that reverts that? Ideally, it would be best if you can write a test case to detect the issue, but it's fine if you can't build one now.

**Comment by sewe** [comment]
> Can you please create a commit that reverts that? Ideally, it would be best if you can write a test case to detect the issue, but it's fine if you can't build one now.

I am afraid “you” is a bit ambiguous. I assume you mean @laeubi, the original reporter. Correct?

**Comment by laeubi** [comment]
@sewe If you can contribute here feel free to do so, I don't plan to work on this issue at the moment.

**Comment by mickaelistria** [comment]
Change was reverted as df649727c7ed85d573b829a5ac7c92bc7cba5db8 . This should be enough.
